

export const SET_AUTH_USER = 'SET_AUTH_USER'
export const RESET_AUTH_STATE = 'RESET_AUTH_STATE'
export const FETCH_CUISINES_SUCCESS = 'FETCH_CUISINES_SUCCESS'
export const FETCH_CUISINE_SUCCESS = 'FETCH_CUISINE_SUCCESS'
export const REQUEST_CUISINE = 'REQUEST_CUISINE'
export const FETCH_PREFERENCES_SUCCESS = 'FETCH_PREFERENCES_SUCCESS'
export const FETCH_PREFERENCE_SUCCESS = 'FETCH_PREFERENCE_SUCCESS'
export const REQUEST_PREFERENCE = 'REQUEST_PREFERENCE'
export const FETCH_USER_PREFERENCES_SUCCESS  = 'FETCH_USER_PREFERENCES_SUCCESS '
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS'
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS'
export const REQUEST_RECIPE = 'REQUEST_RECIPE'

